// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('bookFlight', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('bookFlight', async function() {
    // Test name: bookFlight
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1792x1003 | 
    await driver.manage().window().setRect(1792, 1003)
    // 3 | click | css=.css-10q0vj5:nth-child(2) > h3 | 
    await driver.findElement(By.css(".css-10q0vj5:nth-child(2) > h3")).click()
    // 4 | storeText | css=.css-wwcn44 | cartText
    vars["cartText"] = await driver.findElement(By.css(".css-wwcn44")).getText()
    // 5 | if | ${cartText} === "ADD TO CART" | 
    if (!!await driver.executeScript("return (arguments[0] === \"ADD TO CART\")", vars["cartText"])) {
      // 6 | click | css=.css-wwcn44 | 
      await driver.findElement(By.css(".css-wwcn44")).click()
      // 7 | click | css=.css-1yu82wf:nth-child(2) > svg | 
      await driver.findElement(By.css(".css-1yu82wf:nth-child(2) > svg")).click()
      // 8 | waitForElementPresent | css=.css-wwcn44 | 30000
      await driver.wait(until.elementLocated(By.css(".css-wwcn44")), 30000)
      // 9 | click | css=.css-wwcn44 | 
      await driver.findElement(By.css(".css-wwcn44")).click()
      // 10 | end |  | 
    }
    // 11 | click | css=.css-1yu82wf:nth-child(3) > svg | 
    await driver.findElement(By.css(".css-1yu82wf:nth-child(3) > svg")).click()
    // 12 | waitForElementPresent | css=.css-10q0vj5 | 30000
    await driver.wait(until.elementLocated(By.css(".css-10q0vj5")), 30000)
    // 13 | assertElementPresent | css=.css-10q0vj5 | 
    {
      const elements = await driver.findElements(By.css(".css-10q0vj5"))
      assert(elements.length)
    }
  })
})
