// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Check Profile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Check Profile', async function() {
    // Test name: Check Profile
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1792x1003 | 
    await driver.manage().window().setRect(1792, 1003)
    // 3 | click | css=.css-1yu82wf:nth-child(3) path:nth-child(1) | 
    await driver.findElement(By.css(".css-1yu82wf:nth-child(3) path:nth-child(1)")).click()
    // 4 | assertText | css=h2 | My Trips
    assert(await driver.findElement(By.css("h2")).getText() == "My Trips")
  })
})
