// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('logout', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('logout', async function() {
    // Test name: logout
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1792x1003 | 
    await driver.manage().window().setRect(1792, 1003)
    // 3 | click | css=.css-1y0wpq9 > svg | 
    await driver.findElement(By.css(".css-1y0wpq9 > svg")).click()
    // 4 | assertElementPresent | name=email | 
    {
      const elements = await driver.findElements(By.name("email"))
      assert(elements.length)
    }
  })
})
