// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('remove from cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('remove from cart', async function() {
    // Test name: remove from cart
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | click | css=.css-10q0vj5:nth-child(2) | 
    await driver.findElement(By.css(".css-10q0vj5:nth-child(2)")).click()
    // 3 | waitForElementPresent | css=.css-wwcn44 | 30000
    await driver.wait(until.elementLocated(By.css(".css-wwcn44")), 30000)
    // 4 | click | css=.css-wwcn44 | 
    await driver.findElement(By.css(".css-wwcn44")).click()
    // 5 | click | css=.css-wwcn44 | 
    await driver.findElement(By.css(".css-wwcn44")).click()
    // 6 | click | css=.css-1yu82wf:nth-child(2) path:nth-child(4) | 
    await driver.findElement(By.css(".css-1yu82wf:nth-child(2) path:nth-child(4)")).click()
    // 7 | assertText | css=p | No items in your cart
    assert(await driver.findElement(By.css("p")).getText() == "No items in your cart")
  })
})
